version: "3"
services:
  app:
    build: .
    ports:
      - "8080:8080"
    # environment:
    #   SPRING_DATASOURCE_URL: jdbc:mysql://<your-database-url>:3306/db
    #   SPRING_DATASOURCE_USERNAME: dbuser
    #   SPRING_DATASOURCE_PASSWORD: dbpassword
