version: "3"
services:
  app:
    build: .
    ports:
      - "443:443"
    environment: # 환경 변수 추가
      - SERVER_SSL_KEY-STORE=file:/keystore.p12 # 경로 수정
      - SERVER_SSL_KEY-STORE-PASSWORD=devfeat
      - SERVER_SSL_KEY-STORE-TYPE=PKCS12
      - SERVER_SSL_KEY-ALIAS=feat
