version: "3"
services:
  app:
    build: .
    ports:
      - "443:443"
    environment:
      SERVER_SSL_KEY_STORE: "${SERVER_SSL_KEY_STORE}"
      SERVER_SSL_KEY_STORE_PASSWORD: "${SERVER_SSL_KEY_STORE_PASSWORD}"
      SERVER_SSL_KEY_STORE_TYPE: "${SERVER_SSL_KEY_STORE_TYPE}"
      SERVER_SSL_KEY_ALIAS: "${SERVER_SSL_KEY_ALIAS}"
